// Narrow C ABI for the Electron main process. No scripting interpreter,
// shell interpolation, global input monitoring or Screen Recording access.
#import <AppKit/AppKit.h>
#import <ApplicationServices/ApplicationServices.h>

static char *jsonString(id object) {
    NSData *data = [NSJSONSerialization dataWithJSONObject:object options:0 error:nil];
    if (!data) return NULL;
    return strdup([[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding].UTF8String);
}

void ed_free(void *pointer) { free(pointer); }

int64_t ed_clipboard_change_count(void) {
    @autoreleasepool { return NSPasteboard.generalPasteboard.changeCount; }
}

char *ed_clipboard_files(void) {
    @autoreleasepool {
        NSArray<NSURL *> *urls = [NSPasteboard.generalPasteboard readObjectsForClasses:@[NSURL.class]
            options:@{NSPasteboardURLReadingFileURLsOnlyKey: @YES}];
        NSMutableArray *paths = [NSMutableArray array];
        for (NSURL *url in urls) if (url.isFileURL && url.path) [paths addObject:url.path];
        // Older applications still use NSFilenamesPboardType.
        if (!paths.count) {
            id legacy = [NSPasteboard.generalPasteboard propertyListForType:@"NSFilenamesPboardType"];
            if ([legacy isKindOfClass:NSArray.class]) {
                for (id path in legacy) if ([path isKindOfClass:NSString.class]) [paths addObject:path];
            }
        }
        return jsonString(paths);
    }
}

int ed_clipboard_has_files(void) {
    @autoreleasepool {
        NSArray *types = NSPasteboard.generalPasteboard.types;
        return [types containsObject:NSPasteboardTypeFileURL] || [types containsObject:@"NSFilenamesPboardType"];
    }
}

int ed_clipboard_is_private(void) {
    @autoreleasepool {
        // Password managers and temporary/auto-generated clipboard payloads.
        NSSet *ignored = [NSSet setWithArray:@[@"org.nspasteboard.ConcealedType", @"org.nspasteboard.TransientType",
            @"org.nspasteboard.AutoGeneratedType", @"com.agilebits.onepassword", @"com.typeit4me.clipping"]];
        for (NSString *type in NSPasteboard.generalPasteboard.types) if ([ignored containsObject:type]) return 1;
        return 0;
    }
}

int ed_clipboard_write_files(const char *json) {
    @autoreleasepool {
        if (!json) return 0;
        id paths = [NSJSONSerialization JSONObjectWithData:[[NSString stringWithUTF8String:json]
            dataUsingEncoding:NSUTF8StringEncoding] options:0 error:nil];
        if (![paths isKindOfClass:NSArray.class] || ![paths count]) return 0;
        NSMutableArray *items = [NSMutableArray array];
        for (id path in paths) {
            if (![path isKindOfClass:NSString.class] || ![path isAbsolutePath] ||
                ![NSFileManager.defaultManager fileExistsAtPath:path]) return 0;
            NSPasteboardItem *item = [NSPasteboardItem new];
            [item setString:[NSURL fileURLWithPath:path].absoluteString forType:NSPasteboardTypeFileURL];
            [items addObject:item];
        }
        NSPasteboard *pb = NSPasteboard.generalPasteboard;
        [pb clearContents];
        BOOL ok = [pb writeObjects:items];
        // Materialize every item while its writer is still alive. In particular,
        // file #2 must survive an immediate app/fixture exit, not just file #1.
        for (NSPasteboardItem *item in pb.pasteboardItems)
            for (NSString *type in item.types) (void)[item dataForType:type];
        return ok;
    }
}

int ed_clipboard_write_image(const char *imagePath, const char *filePath) {
    @autoreleasepool {
        if (!imagePath || !filePath) return 0;
        NSImage *image = [[NSImage alloc] initWithContentsOfFile:[NSString stringWithUTF8String:imagePath]];
        NSString *path = [NSString stringWithUTF8String:filePath];
        if (!image || ![NSFileManager.defaultManager fileExistsAtPath:path]) return 0;
        NSPasteboard *pb = NSPasteboard.generalPasteboard;
        [pb clearContents];
        // Image readers get full bitmap data; Finder gets a named file URL.
        NSPasteboardItem *item = [NSPasteboardItem new];
        [item setData:image.TIFFRepresentation forType:NSPasteboardTypeTIFF];
        [item setString:[NSURL fileURLWithPath:path].absoluteString forType:NSPasteboardTypeFileURL];
        return [pb writeObjects:@[item]];
    }
}

int ed_frontmost_pid(void) {
    @autoreleasepool { return NSWorkspace.sharedWorkspace.frontmostApplication.processIdentifier; }
}

int ed_activate_pid(int pid) {
    @autoreleasepool {
        if (pid <= 0 || pid == NSProcessInfo.processInfo.processIdentifier) return 0;
        NSRunningApplication *target = [NSRunningApplication runningApplicationWithProcessIdentifier:pid];
        return target && !target.terminated && [target activateWithOptions:NSApplicationActivateIgnoringOtherApps];
    }
}

int ed_accessibility_trusted(void) { return AXIsProcessTrusted(); }

int ed_paste(int expectedPid) {
    @autoreleasepool {
        // Recheck the intended recipient at key-send time, after any delay.
        if (!AXIsProcessTrusted() || expectedPid <= 0 || ed_frontmost_pid() != expectedPid ||
            expectedPid == NSProcessInfo.processInfo.processIdentifier) return 0;
        CGEventSourceRef source = CGEventSourceCreate(kCGEventSourceStateCombinedSessionState);
        CGEventRef down = CGEventCreateKeyboardEvent(source, 9, true); // physical V
        CGEventRef up = CGEventCreateKeyboardEvent(source, 9, false);
        if (!down || !up) {
            if (down) CFRelease(down);
            if (up) CFRelease(up);
            if (source) CFRelease(source);
            return 0;
        }
        CGEventSetFlags(down, kCGEventFlagMaskCommand);
        CGEventSetFlags(up, kCGEventFlagMaskCommand);
        CGEventPost(kCGHIDEventTap, down);
        CGEventPost(kCGHIDEventTap, up);
        CFRelease(down); CFRelease(up);
        if (source) CFRelease(source);
        return 1;
    }
}

int ed_frontmost_fullscreen(void) {
    @autoreleasepool {
        int pid = ed_frontmost_pid();
        if (!AXIsProcessTrusted() || pid <= 0 || pid == NSProcessInfo.processInfo.processIdentifier) return 0;
        AXUIElementRef app = AXUIElementCreateApplication(pid);
        // Avoid a hung application blocking Electron's event loop for seconds.
        AXUIElementSetMessagingTimeout(app, 0.05);
        CFTypeRef window = NULL, value = NULL;
        int fullscreen = 0;
        if (AXUIElementCopyAttributeValue(app, kAXFocusedWindowAttribute, &window) == kAXErrorSuccess && window) {
            if (AXUIElementCopyAttributeValue((AXUIElementRef)window, CFSTR("AXFullScreen"), &value) == kAXErrorSuccess && value)
                fullscreen = CFGetTypeID(value) == CFBooleanGetTypeID() && CFBooleanGetValue(value);
        }
        if (value) CFRelease(value);
        if (window) CFRelease(window);
        CFRelease(app);
        return fullscreen;
    }
}
